# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Mock-server:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: clone mock-server
      run: git clone https://github.com/upanshu21/open-weather-mock-api.git
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: run mock server
      working-directory: ./open-weather-mock-api
      run : mvn spring-boot:run
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./MyLibrary
      run: swift build -v
    - name: Run tests
      working-directory: ./MyLibrary
      run: swift test -v
